import type { Metadata } from 'next'
import './globals.css'
import { Poppins as FontSans } from 'next/font/google'
import { cn } from '@/lib/utils'
import React from 'react'

const fontsSans = FontSans({
  subsets: ['latin'],
  weight: ['400', '600'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Ecommerce Next 14 with Basir',
  description: 'Generated by create-next-app@latest',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontsSans.variable
        )}
      >
        {children}
      </body>
    </html>
  )
}
