import Head from 'next/head';
import Link from 'next/link';
import './globals.css';
import { Inter } from 'next/font/google';
import { Store, StoreProvider } from '@/utils/Store';
import { useContext } from 'react';
import Nav from '@/components/Nav';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Basir Ecommerce Next Tailwind',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <Head>
        <title>Basir Ecommerce Next Tailwind Mongo</title>
        <meta
          name="description"
          content="Generated by create next app latest"
        />
        <Link rel="icon" href="./favicon.ico" />
      </Head>
      
        <body className="flex min-h-screen flex-col justify-between">
          <StoreProvider>
            <header>
              <nav className="flex h-12 items-center px-4 justify-between shadow-md">
                <Link href="/" className="text-lg font-bold">
                  Ecommerce
                </Link>
                <div>
                  <Nav/>
                </div>
              </nav>
            </header>
            <main className="container m-auto mt-4 px-4">{children}</main>
            <footer className="flex h-10 justify-center items-center shadow-inner">
              Copyright &copy; 2022 Ecommerce
            </footer>
          </StoreProvider>
        </body>
    </html>
  )
}
